theme: jekyll-theme-architect
title: sjay
description: such as NP-Complete
language: zh
output:
  html_document:
    includes:
      in_header: header.html
      after_body: after.html
<link rel="icon" type="image/png" href="https://ahsjlin.github.io/bot.png">
